// Copyright 2020 Silicon Laboratories, Inc.
//
//

/********************************************************************
 * Autogenerated file, do not edit.
 *******************************************************************/

#ifndef __GATT_DB_H
#define __GATT_DB_H

#include "bg_gattdb_def.h"

extern const struct bg_gattdb_def bg_gattdb_data;

#define gattdb_service_changed_char             3
#define gattdb_database_hash                    6
#define gattdb_client_support_features          8
#define gattdb_button_state                    11
#define gattdb_device_name                     15
#define gattdb_descriptor_value_changed         27
#define gattdb_apparent_wind_direction         30
#define gattdb_es_measurement                  31
#define gattdb_es_trigger_setting              32
#define gattdb_es_configuration                33
#define gattdb_characteristic_user_description         34
#define gattdb_valid_range                     35
#define gattdb_apparent_wind_speed             37
#define gattdb_es_measurement_2                38
#define gattdb_es_trigger_setting_2            39
#define gattdb_es_configuration_2              40
#define gattdb_characteristic_user_description_2         41
#define gattdb_valid_range_2                   42
#define gattdb_dew_point                       44
#define gattdb_es_measurement_3                45
#define gattdb_es_trigger_setting_3            46
#define gattdb_es_configuration_3              47
#define gattdb_characteristic_user_description_3         48
#define gattdb_valid_range_3                   49
#define gattdb_elevation                       51
#define gattdb_es_measurement_4                52
#define gattdb_es_trigger_setting_4            53
#define gattdb_es_configuration_4              54
#define gattdb_characteristic_user_description_4         55
#define gattdb_valid_range_4                   56
#define gattdb_gust_factor                     58
#define gattdb_es_measurement_5                59
#define gattdb_es_trigger_setting_5            60
#define gattdb_es_configuration_5              61
#define gattdb_characteristic_user_description_5         62
#define gattdb_valid_range_5                   63
#define gattdb_heat_index                      65
#define gattdb_es_measurement_6                66
#define gattdb_es_trigger_setting_6            67
#define gattdb_es_configuration_6              68
#define gattdb_characteristic_user_description_6         69
#define gattdb_valid_range_6                   70
#define gattdb_humidity                        72
#define gattdb_es_measurement_7                73
#define gattdb_es_trigger_setting_7            74
#define gattdb_es_configuration_7              75
#define gattdb_characteristic_user_description_7         76
#define gattdb_valid_range_7                   77
#define gattdb_irradiance                      79
#define gattdb_es_measurement_8                80
#define gattdb_es_trigger_setting_8            81
#define gattdb_es_configuration_8              82
#define gattdb_characteristic_user_description_8         83
#define gattdb_valid_range_8                   84
#define gattdb_pollen_concentration            86
#define gattdb_es_measurement_9                87
#define gattdb_es_trigger_setting_9            88
#define gattdb_es_configuration_9              89
#define gattdb_characteristic_user_description_9         90
#define gattdb_valid_range_9                   91
#define gattdb_rainfall                        93
#define gattdb_es_measurement_10               94
#define gattdb_es_trigger_setting_10           95
#define gattdb_es_configuration_10             96
#define gattdb_characteristic_user_description_10         97
#define gattdb_valid_range_10                  98
#define gattdb_pressure                       100
#define gattdb_es_measurement_11              101
#define gattdb_es_trigger_setting_11          102
#define gattdb_es_configuration_11            103
#define gattdb_characteristic_user_description_11        104
#define gattdb_valid_range_11                 105
#define gattdb_temperature                    107
#define gattdb_es_measurement_12              108
#define gattdb_es_trigger_setting_12          109
#define gattdb_es_configuration_12            110
#define gattdb_characteristic_user_description_12        111
#define gattdb_valid_range_12                 112
#define gattdb_true_wind_direction            114
#define gattdb_es_measurement_13              115
#define gattdb_es_trigger_setting_13          116
#define gattdb_es_configuration_13            117
#define gattdb_characteristic_user_description_13        118
#define gattdb_valid_range_13                 119
#define gattdb_true_wind_speed                121
#define gattdb_es_measurement_14              122
#define gattdb_es_trigger_setting_14          123
#define gattdb_es_configuration_14            124
#define gattdb_characteristic_user_description_14        125
#define gattdb_valid_range_14                 126
#define gattdb_uv_index                       128
#define gattdb_es_measurement_15              129
#define gattdb_es_trigger_setting_15          130
#define gattdb_es_configuration_15            131
#define gattdb_characteristic_user_description_15        132
#define gattdb_valid_range_15                 133
#define gattdb_wind_chill                     135
#define gattdb_es_measurement_16              136
#define gattdb_es_trigger_setting_16          137
#define gattdb_es_configuration_16            138
#define gattdb_characteristic_user_description_16        139
#define gattdb_valid_range_16                 140
#define gattdb_barometric_pressure_trend        142
#define gattdb_es_measurement_17              143
#define gattdb_es_trigger_setting_17          144
#define gattdb_es_configuration_17            145
#define gattdb_characteristic_user_description_17        146
#define gattdb_valid_range_17                 147
#define gattdb_magnetic_declination           149
#define gattdb_es_measurement_18              150
#define gattdb_es_trigger_setting_18          151
#define gattdb_es_configuration_18            152
#define gattdb_characteristic_user_description_18        153
#define gattdb_valid_range_18                 154
#define gattdb_magnetic_flux_density_2D        156
#define gattdb_es_measurement_19              157
#define gattdb_es_trigger_setting_19          158
#define gattdb_es_configuration_19            159
#define gattdb_characteristic_user_description_19        160
#define gattdb_valid_range_19                 161
#define gattdb_magnetic_flux_density_3D        163
#define gattdb_es_measurement_20              164
#define gattdb_es_trigger_setting_20          165
#define gattdb_es_configuration_20            166
#define gattdb_characteristic_user_description_20        167
#define gattdb_valid_range_20                 168
#define gattdb_temperature_measurement        171
#define gattdb_temperature_type               174
#define gattdb_intermediate_temperature        176
#define gattdb_measurement_interval           179
#define gattdb_valid_range_21                 181
#define gattdb_tx_power_level                 184
#define gattdb_ota_control                    187
#define gattdb_ota_data                       189

#endif
