// Copyright 2020 Silicon Laboratories, Inc.
//
//

/********************************************************************
 * Autogenerated file, do not edit.
 *******************************************************************/

#ifndef __GATT_DB_H
#define __GATT_DB_H

#include "bg_gattdb_def.h"

extern const struct bg_gattdb_def bg_gattdb_data;

#define gattdb_service_changed_char             3
#define gattdb_database_hash                    6
#define gattdb_client_support_features          8
#define gattdb_button_state                    11
#define gattdb_device_name                     15
#define gattdb_ota_control                     27
#define gattdb_ota_data                        29
#define gattdb_temperature_measurement         32
#define gattdb_temperature_type                35
#define gattdb_intermediate_temperature         37
#define gattdb_measurement_interval            40
#define gattdb_valid_range                     42
#define gattdb_descriptor_value_changed         45
#define gattdb_apparent_wind_direction         48
#define gattdb_es_measurement                  49
#define gattdb_es_trigger_setting              50
#define gattdb_es_configuration                51
#define gattdb_characteristic_user_description         52
#define gattdb_valid_range_2                   53
#define gattdb_apparent_wind_speed             55
#define gattdb_es_measurement_2                56
#define gattdb_es_trigger_setting_2            57
#define gattdb_es_configuration_2              58
#define gattdb_characteristic_user_description_2         59
#define gattdb_valid_range_3                   60
#define gattdb_dew_point                       62
#define gattdb_es_measurement_3                63
#define gattdb_es_trigger_setting_3            64
#define gattdb_es_configuration_3              65
#define gattdb_characteristic_user_description_3         66
#define gattdb_valid_range_4                   67
#define gattdb_elevation                       69
#define gattdb_es_measurement_4                70
#define gattdb_es_trigger_setting_4            71
#define gattdb_es_configuration_4              72
#define gattdb_characteristic_user_description_4         73
#define gattdb_valid_range_5                   74
#define gattdb_gust_factor                     76
#define gattdb_es_measurement_5                77
#define gattdb_es_trigger_setting_5            78
#define gattdb_es_configuration_5              79
#define gattdb_characteristic_user_description_5         80
#define gattdb_valid_range_6                   81
#define gattdb_heat_index                      83
#define gattdb_es_measurement_6                84
#define gattdb_es_trigger_setting_6            85
#define gattdb_es_configuration_6              86
#define gattdb_characteristic_user_description_6         87
#define gattdb_valid_range_7                   88
#define gattdb_humidity                        90
#define gattdb_es_measurement_7                91
#define gattdb_es_trigger_setting_7            92
#define gattdb_es_configuration_7              93
#define gattdb_characteristic_user_description_7         94
#define gattdb_valid_range_8                   95
#define gattdb_irradiance                      97
#define gattdb_es_measurement_8                98
#define gattdb_es_trigger_setting_8            99
#define gattdb_es_configuration_8             100
#define gattdb_characteristic_user_description_8        101
#define gattdb_valid_range_9                  102
#define gattdb_pollen_concentration           104
#define gattdb_es_measurement_9               105
#define gattdb_es_trigger_setting_9           106
#define gattdb_es_configuration_9             107
#define gattdb_characteristic_user_description_9        108
#define gattdb_valid_range_10                 109
#define gattdb_rainfall                       111
#define gattdb_es_measurement_10              112
#define gattdb_es_trigger_setting_10          113
#define gattdb_es_configuration_10            114
#define gattdb_characteristic_user_description_10        115
#define gattdb_valid_range_11                 116
#define gattdb_pressure                       118
#define gattdb_es_measurement_11              119
#define gattdb_es_trigger_setting_11          120
#define gattdb_es_configuration_11            121
#define gattdb_characteristic_user_description_11        122
#define gattdb_valid_range_12                 123
#define gattdb_temperature                    125
#define gattdb_es_measurement_12              126
#define gattdb_es_trigger_setting_12          127
#define gattdb_es_configuration_12            128
#define gattdb_characteristic_user_description_12        129
#define gattdb_valid_range_13                 130
#define gattdb_true_wind_direction            132
#define gattdb_es_measurement_13              133
#define gattdb_es_trigger_setting_13          134
#define gattdb_es_configuration_13            135
#define gattdb_characteristic_user_description_13        136
#define gattdb_valid_range_14                 137
#define gattdb_true_wind_speed                139
#define gattdb_es_measurement_14              140
#define gattdb_es_trigger_setting_14          141
#define gattdb_es_configuration_14            142
#define gattdb_characteristic_user_description_14        143
#define gattdb_valid_range_15                 144
#define gattdb_uv_index                       146
#define gattdb_es_measurement_15              147
#define gattdb_es_trigger_setting_15          148
#define gattdb_es_configuration_15            149
#define gattdb_characteristic_user_description_15        150
#define gattdb_valid_range_16                 151
#define gattdb_wind_chill                     153
#define gattdb_es_measurement_16              154
#define gattdb_es_trigger_setting_16          155
#define gattdb_es_configuration_16            156
#define gattdb_characteristic_user_description_16        157
#define gattdb_valid_range_17                 158
#define gattdb_barometric_pressure_trend        160
#define gattdb_es_measurement_17              161
#define gattdb_es_trigger_setting_17          162
#define gattdb_es_configuration_17            163
#define gattdb_characteristic_user_description_17        164
#define gattdb_valid_range_18                 165
#define gattdb_magnetic_declination           167
#define gattdb_es_measurement_18              168
#define gattdb_es_trigger_setting_18          169
#define gattdb_es_configuration_18            170
#define gattdb_characteristic_user_description_18        171
#define gattdb_valid_range_19                 172
#define gattdb_magnetic_flux_density_2D        174
#define gattdb_es_measurement_19              175
#define gattdb_es_trigger_setting_19          176
#define gattdb_es_configuration_19            177
#define gattdb_characteristic_user_description_19        178
#define gattdb_valid_range_20                 179
#define gattdb_magnetic_flux_density_3D        181
#define gattdb_es_measurement_20              182
#define gattdb_es_trigger_setting_20          183
#define gattdb_es_configuration_20            184
#define gattdb_characteristic_user_description_20        185
#define gattdb_valid_range_21                 186
#define gattdb_tx_power_level                 189

#endif
