// Copyright 2020 Silicon Laboratories, Inc.
//
//

/********************************************************************
 * Autogenerated file, do not edit.
 *******************************************************************/

#ifndef __GATT_DB_H
#define __GATT_DB_H

#include "bg_gattdb_def.h"

extern const struct bg_gattdb_def bg_gattdb_data;

#define gattdb_service_changed_char             3
#define gattdb_database_hash                    6
#define gattdb_client_support_features          8
#define gattdb_button_state                    11
#define gattdb_device_name                     15
#define gattdb_temperature_measurement         27
#define gattdb_temperature_type                30
#define gattdb_intermediate_temperature         32
#define gattdb_measurement_interval            35
#define gattdb_valid_range                     37
#define gattdb_descriptor_value_changed         40
#define gattdb_apparent_wind_direction         43
#define gattdb_es_measurement                  44
#define gattdb_es_trigger_setting              45
#define gattdb_es_configuration                46
#define gattdb_characteristic_user_description         47
#define gattdb_valid_range_2                   48
#define gattdb_apparent_wind_speed             50
#define gattdb_es_measurement_2                51
#define gattdb_es_trigger_setting_2            52
#define gattdb_es_configuration_2              53
#define gattdb_characteristic_user_description_2         54
#define gattdb_valid_range_3                   55
#define gattdb_dew_point                       57
#define gattdb_es_measurement_3                58
#define gattdb_es_trigger_setting_3            59
#define gattdb_es_configuration_3              60
#define gattdb_characteristic_user_description_3         61
#define gattdb_valid_range_4                   62
#define gattdb_elevation                       64
#define gattdb_es_measurement_4                65
#define gattdb_es_trigger_setting_4            66
#define gattdb_es_configuration_4              67
#define gattdb_characteristic_user_description_4         68
#define gattdb_valid_range_5                   69
#define gattdb_gust_factor                     71
#define gattdb_es_measurement_5                72
#define gattdb_es_trigger_setting_5            73
#define gattdb_es_configuration_5              74
#define gattdb_characteristic_user_description_5         75
#define gattdb_valid_range_6                   76
#define gattdb_heat_index                      78
#define gattdb_es_measurement_6                79
#define gattdb_es_trigger_setting_6            80
#define gattdb_es_configuration_6              81
#define gattdb_characteristic_user_description_6         82
#define gattdb_valid_range_7                   83
#define gattdb_humidity                        85
#define gattdb_es_measurement_7                86
#define gattdb_es_trigger_setting_7            87
#define gattdb_es_configuration_7              88
#define gattdb_characteristic_user_description_7         89
#define gattdb_valid_range_8                   90
#define gattdb_irradiance                      92
#define gattdb_es_measurement_8                93
#define gattdb_es_trigger_setting_8            94
#define gattdb_es_configuration_8              95
#define gattdb_characteristic_user_description_8         96
#define gattdb_valid_range_9                   97
#define gattdb_pollen_concentration            99
#define gattdb_es_measurement_9               100
#define gattdb_es_trigger_setting_9           101
#define gattdb_es_configuration_9             102
#define gattdb_characteristic_user_description_9        103
#define gattdb_valid_range_10                 104
#define gattdb_rainfall                       106
#define gattdb_es_measurement_10              107
#define gattdb_es_trigger_setting_10          108
#define gattdb_es_configuration_10            109
#define gattdb_characteristic_user_description_10        110
#define gattdb_valid_range_11                 111
#define gattdb_pressure                       113
#define gattdb_es_measurement_11              114
#define gattdb_es_trigger_setting_11          115
#define gattdb_es_configuration_11            116
#define gattdb_characteristic_user_description_11        117
#define gattdb_valid_range_12                 118
#define gattdb_temperature                    120
#define gattdb_es_measurement_12              121
#define gattdb_es_trigger_setting_12          122
#define gattdb_es_configuration_12            123
#define gattdb_characteristic_user_description_12        124
#define gattdb_valid_range_13                 125
#define gattdb_true_wind_direction            127
#define gattdb_es_measurement_13              128
#define gattdb_es_trigger_setting_13          129
#define gattdb_es_configuration_13            130
#define gattdb_characteristic_user_description_13        131
#define gattdb_valid_range_14                 132
#define gattdb_true_wind_speed                134
#define gattdb_es_measurement_14              135
#define gattdb_es_trigger_setting_14          136
#define gattdb_es_configuration_14            137
#define gattdb_characteristic_user_description_14        138
#define gattdb_valid_range_15                 139
#define gattdb_uv_index                       141
#define gattdb_es_measurement_15              142
#define gattdb_es_trigger_setting_15          143
#define gattdb_es_configuration_15            144
#define gattdb_characteristic_user_description_15        145
#define gattdb_valid_range_16                 146
#define gattdb_wind_chill                     148
#define gattdb_es_measurement_16              149
#define gattdb_es_trigger_setting_16          150
#define gattdb_es_configuration_16            151
#define gattdb_characteristic_user_description_16        152
#define gattdb_valid_range_17                 153
#define gattdb_barometric_pressure_trend        155
#define gattdb_es_measurement_17              156
#define gattdb_es_trigger_setting_17          157
#define gattdb_es_configuration_17            158
#define gattdb_characteristic_user_description_17        159
#define gattdb_valid_range_18                 160
#define gattdb_magnetic_declination           162
#define gattdb_es_measurement_18              163
#define gattdb_es_trigger_setting_18          164
#define gattdb_es_configuration_18            165
#define gattdb_characteristic_user_description_18        166
#define gattdb_valid_range_19                 167
#define gattdb_magnetic_flux_density_2D        169
#define gattdb_es_measurement_19              170
#define gattdb_es_trigger_setting_19          171
#define gattdb_es_configuration_19            172
#define gattdb_characteristic_user_description_19        173
#define gattdb_valid_range_20                 174
#define gattdb_magnetic_flux_density_3D        176
#define gattdb_es_measurement_20              177
#define gattdb_es_trigger_setting_20          178
#define gattdb_es_configuration_20            179
#define gattdb_characteristic_user_description_20        180
#define gattdb_valid_range_21                 181
#define gattdb_tx_power_level                 184

#endif
